[package]
name = "tongji-undergrad-thesis-typst"
version = "0.1.0"
entrypoint = "main.typ"
authors = ["TJ-CSCCG <https://github.com/TJ-CSCCG>"]
license = "MIT"
description = "同济大学本科生毕业设计论文模板 | Tongji University Undergraduate Thesis Template"
repository = "https://github.com/TJ-CSCCG/tongji-undergrad-thesis-typst.git"
keywords = ["Tongji University", "thesis", "undergraduate"]
categories = ["thesis"]
exclude = []

[template]
path = "./"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"
